[wallpapers]
1 = "/home/samsja/Pictures/bg/1024.jpg"
2 = "/home/samsja/Pictures/bg/1023.jpg"
3 = "/home/samsja/Pictures/bg/710.jpg"
4 = "/home/samsja/Pictures/bg/1025.jpg"
5 = "/home/samsja/Pictures/bg/1.png"
6 = "/home/samsja/Pictures/bg/sunny.png"
7 = "/home/samsja/Pictures/bg/958.jpg"
8 = "/home/samsja/Pictures/bg/op.jpg"
9 = "/home/samsja/Pictures/bg/laputa.jpg"
