add_newline = false

[kubernetes]
disabled = true

# [cmd_duration]
# min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
# format = " took [$duration]($style)"
#
[git_branch]
#format = " [$symbol$branch]($style) "
format = " [$branch]($style) "
symbol = "🍣 "

[hostname]
disabled = true

[julia]
disable = false

[memory_usage]
disabled = false

[package]
disabled = true

[time]
disabled = true

[gcloud]
disabled = true 

[username]
style_user = "bold dimmed blue"
show_always = false

[rust]
disabled = false

[nodejs]
disabled = true
