[colors.bright]
black = "0x585858"
blue = "0x7cafc2"
cyan = "0x1ABB9B"
green = "0xddffa7"
magenta = "0xba8baf"
red = "0xff8b92"
white = "0xf8f8f8"
yellow = "0xf7ca88"

[colors.normal]
black = "0x222d31"
blue = "0x7cafc2"
cyan = "0x1ABB9B"
green = "0xc3e88d"
magenta = "0xba8baf"
red = "0xf07178"
white = "0xd8d8d8"
yellow = "0xf7ca88"

[colors.primary]
background = "0x222d31"
foreground = "0xd0d0d0"

[font]
size = 12

[window]
opacity = 0.95
